Revert "Merge branch 'main' into release/2.0"
This reverts commit ef1d5fd2cd77e15c3b9a2eb34c409c48e4a58559, reversing
changes made to f215885d14b027ccc8e12afc3428d56147ce038f.

diff --git a/tools/chpl-language-server/chpl-shim b/tools/chpl-language-server/chpl-shim
--- a/tools/chpl-language-server/chpl-shim
+++ b/tools/chpl-language-server/chpl-shim
@@ -20,14 +20,8 @@
 #
 
 if [ -z "$CHPL_HOME" ]; then
-  # We need CHPL_HOME to find run-in-venv.bash. Try falling back to a
-  # compiler in PATH.
-  if output=$(chpl --print-bootstrap-commands); then
-    eval "$output"
-  else
-    echo "Error: CHPL_HOME is not set" 1>&2
-    exit 1
-  fi
+  echo "Error: CHPL_HOME is not set"
+  exit 1
 fi
 
 exec $CHPL_HOME/util/config/run-in-venv-with-python-bindings.bash \
